perf: Add stub definition of topology_core_has_smt()
Currently 32 bit arm configurations without CONFIG_GENEIRC_ARCH_TOPOLOGY
fail to build:

/build/stage/linux/drivers/perf/arm_pmu.c: In function ‘armpmu_register’:
/build/stage/linux/drivers/perf/arm_pmu.c:935:24: error: implicit declaration of
 function ‘topology_core_has_smt’; did you mean ‘topology_core_cpumask’? [-Wimpl
icit-function-declaration]
  935 |         pmu->has_smt = topology_core_has_smt(cpumask_first(&pmu->support
ed_cpus));
      |                        ^~~~~~~~~~~~~~~~~~~~~
      |                        topology_core_cpumask

since this function is only defined within a configuration guard.  Add
a stub for other architectures since it is expected that anything adding
SMT support will be using the generic topology implementation.

Fixes: c3d78c34ad00 ("perf: arm_pmuv3: Don't use PMCCNTR_EL0 on SMT cores")
Signed-off-by: Mark Brown <broonie@kernel.org>